export const CQRS_OPTIONS = 'CQRS_OPTIONS';
export const CQRS_EVENT_STORE = 'CQRS_EVENT_STORE';
export const CQRS_SNAPSHOT_STORE = 'CQRS_SNAPSHOT_STORE';
export const CQRS_COMMAND_BUS = 'CQRS_COMMAND_BUS';
export const CQRS_REPLAY_SERVICE = 'CQRS_REPLAY_SERVICE';
export const CQRS_OUTBOX_PROCESSOR = 'CQRS_OUTBOX_PROCESSOR';
