import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  clean: true,
  sourcemap: true,
  external: [
    '@nestjs/common',
    '@nestjs/core',
    '@nestjs/platform-express',
    '@nestjs/mongoose',
    '@nestjs/terminus',
    'mongoose',
    'rxjs',
    'ioredis',
    'memjs',
    'jsonwebtoken',
    'otpauth',
    'prom-client',
    'pino',
    'pino-pretty',
    'bullmq',
    '@opentelemetry/sdk-node',
    '@opentelemetry/api',
    '@opentelemetry/auto-instrumentations-node',
    '@opentelemetry/exporter-trace-otlp-http',
    '@nestjs/microservices',
    '@grpc/grpc-js',
    '@grpc/proto-loader',
    '@nestjs/swagger',
    '@nestjs/websockets',
    '@nestjs/platform-socket.io',
    '@socket.io/redis-adapter',
    'socket.io',
    '@aws-sdk/client-s3',
    '@aws-sdk/s3-request-presigner',
    '@google-cloud/storage',
    'dotenv',
  ],
});
