import { defineConfig } from 'tsup';

const modules = [
  'alerts',
  'auth',
  'cache',
  'common',
  'config',
  'contracts',
  'correlation',
  'cqrs',
  'database',
  'deploy',
  'events',
  'graph',
  'health',
  'inter-service-auth',
  'layers',
  'logging',
  'metrics',
  'payments',
  'queue',
  'resilience',
  'rpc',
  'shutdown',
  'storage',
  'swagger',
  'tenancy',
  'testing',
  'tracing',
  'transport',
  'versioning',
  'websocket',
];

const external = [
  // dependencies
  'dotenv',
  'joi',
  // peerDependencies
  '@aws-sdk/client-s3',
  '@aws-sdk/client-secrets-manager',
  '@aws-sdk/s3-request-presigner',
  '@google-cloud/storage',
  '@grpc/grpc-js',
  '@grpc/proto-loader',
  '@nestjs/common',
  '@nestjs/core',
  '@nestjs/microservices',
  '@nestjs/mongoose',
  '@nestjs/platform-express',
  '@nestjs/platform-socket.io',
  '@nestjs/swagger',
  '@nestjs/terminus',
  '@nestjs/websockets',
  '@opentelemetry/api',
  '@opentelemetry/auto-instrumentations-node',
  '@opentelemetry/exporter-jaeger',
  '@opentelemetry/exporter-trace-otlp-http',
  '@opentelemetry/exporter-zipkin',
  '@opentelemetry/sdk-node',
  '@opentelemetry/sdk-trace-base',
  '@socket.io/redis-adapter',
  'bullmq',
  'class-validator',
  'ioredis',
  'jsonwebtoken',
  'memjs',
  'mongoose',
  'otpauth',
  'passport-github2',
  'passport-google-oauth20',
  'pino',
  'pino-pretty',
  'prom-client',
  'rxjs',
  'socket.io',
  'supertest',
];

export default defineConfig([
  // Root entry — single bundle (backwards compatible)
  {
    entry: ['src/index.ts'],
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    clean: true,
    sourcemap: true,
    external,
  },
  // Per-module entries — tree-shakeable sub-paths
  {
    entry: modules.map((m) => `src/${m}/index.ts`),
    outDir: 'dist',
    format: ['cjs', 'esm'],
    dts: true,
    splitting: false,
    clean: false,
    sourcemap: true,
    external,
  },
]);
