import { Injectable } from '@nestjs/common';

/**
 * Database schema categories for multi-schema architecture.
 * Each schema groups related tables for query optimization and isolation.
 */
export enum DatabaseSchema {
  /** Roles, permissions, org hierarchy — rarely changes, cacheable */
  MASTERDATA = 'masterdata',
  /** Permission definitions, scope/policy config — read-heavy, cacheable */
  METADATA = 'metadata',
  /** Users, assignments, sessions, tokens — read/write balanced */
  USERDATA = 'userdata',
  /** Audit entries, security events — write-heavy, append-only */
  ANALYTICS = 'analytics',
  /** Aggregated metrics, usage counters — write-heavy, periodic rollup */
  STATISTICS = 'statistics',
  /** Default public schema */
  PUBLIC = 'public',
}

/** Default schema assignments for built-in entities */
export const DEFAULT_SCHEMA_MAP: Record<string, DatabaseSchema> = {
  // masterdata
  roles: DatabaseSchema.MASTERDATA,
  permissions: DatabaseSchema.MASTERDATA,
  role_permissions: DatabaseSchema.MASTERDATA,
  role_hierarchy: DatabaseSchema.MASTERDATA,
  organizations: DatabaseSchema.MASTERDATA,
  departments: DatabaseSchema.MASTERDATA,
  teams: DatabaseSchema.MASTERDATA,

  // metadata
  permission_definitions: DatabaseSchema.METADATA,
  scope_definitions: DatabaseSchema.METADATA,
  policy_definitions: DatabaseSchema.METADATA,

  // userdata
  users: DatabaseSchema.USERDATA,
  user_roles: DatabaseSchema.USERDATA,
  user_permissions: DatabaseSchema.USERDATA,
  user_org_memberships: DatabaseSchema.USERDATA,
  refresh_tokens: DatabaseSchema.USERDATA,
  sessions: DatabaseSchema.USERDATA,

  // analytics
  audit_entries: DatabaseSchema.ANALYTICS,
  security_events: DatabaseSchema.ANALYTICS,
  login_attempts: DatabaseSchema.ANALYTICS,

  // statistics
  access_stats: DatabaseSchema.STATISTICS,
  permission_usage: DatabaseSchema.STATISTICS,
  scope_hits: DatabaseSchema.STATISTICS,
  policy_evaluations: DatabaseSchema.STATISTICS,
};

export interface SchemaRegistryOptions {
  /** Override default schema assignments */
  overrides?: Record<string, DatabaseSchema | string>;
  /** Schemas to create on init. Default: all DatabaseSchema values */
  schemas?: string[];
  /** Whether to auto-create schemas on connect. Default: true in dev */
  autoCreate?: boolean;
}

/**
 * SchemaRegistry — maps entity/table names to database schemas.
 * Used by PrismaBaseRepository and migration tools to route queries.
 */
@Injectable()
export class SchemaRegistry {
  private readonly map: Map<string, string>;
  private readonly schemas: Set<string>;

  constructor(options?: SchemaRegistryOptions) {
    // Merge defaults with overrides
    this.map = new Map(Object.entries(DEFAULT_SCHEMA_MAP));
    if (options?.overrides) {
      for (const [entity, schema] of Object.entries(options.overrides)) {
        this.map.set(entity, schema);
      }
    }

    // Collect all unique schemas
    this.schemas = new Set(
      options?.schemas ?? Object.values(DatabaseSchema),
    );
  }

  /** Get schema for an entity/table name */
  getSchema(entityName: string): string {
    return this.map.get(entityName) ?? DatabaseSchema.PUBLIC;
  }

  /** Set schema for an entity/table name */
  setSchema(entityName: string, schema: string): void {
    this.map.set(entityName, schema);
  }

  /** Get the fully qualified table name: schema.table */
  qualifiedName(entityName: string): string {
    const schema = this.getSchema(entityName);
    return schema === DatabaseSchema.PUBLIC ? entityName : `${schema}.${entityName}`;
  }

  /** Get all entity names in a specific schema */
  getEntitiesInSchema(schema: string): string[] {
    const entities: string[] = [];
    for (const [entity, s] of this.map) {
      if (s === schema) entities.push(entity);
    }
    return entities;
  }

  /** Get all registered schemas */
  getSchemas(): string[] {
    return [...this.schemas];
  }

  /** Get the full mapping as a plain object */
  getMapping(): Record<string, string> {
    return Object.fromEntries(this.map);
  }

  /** Generate SQL to create all schemas */
  generateCreateSchemasSql(): string {
    return [...this.schemas]
      .filter(s => s !== DatabaseSchema.PUBLIC)
      .map(s => `CREATE SCHEMA IF NOT EXISTS "${s}";`)
      .join('\n');
  }

  /** Generate Prisma schema annotations for all entities */
  generatePrismaSchemaMap(): string {
    const lines: string[] = [
      '// Generated by SchemaRegistry — paste into prisma/schema.prisma',
      '// Requires: previewFeatures = ["multiSchema"]',
      `// Schemas: ${[...this.schemas].join(', ')}`,
      '',
    ];
    const bySchema = new Map<string, string[]>();
    for (const [entity, schema] of this.map) {
      if (!bySchema.has(schema)) bySchema.set(schema, []);
      bySchema.get(schema)!.push(entity);
    }
    for (const [schema, entities] of bySchema) {
      lines.push(`// ── ${schema} ──`);
      for (const e of entities) {
        lines.push(`// ${e} → @@schema("${schema}")`);
      }
      lines.push('');
    }
    return lines.join('\n');
  }
}

export const SCHEMA_REGISTRY = 'BOOT_SCHEMA_REGISTRY';
