export interface ModuleInfo {
  name: string;
  category: string;
  kano: "Must-be" | "Attractive" | "One-dimensional";
  description: string;
  config: string;
  methods: string[];
  exports: string[];
}

export const modules: ModuleInfo[] = [
  {
    name: "DatabaseModule",
    category: "Database",
    kano: "Attractive",
    description: "Config-driven multi-connection MongoDB with reader/writer split",
    config: `database: {\n  connections: {\n    master: { writerUri: 'mongodb://...' }\n  }\n}`,
    methods: ["forFeature()", "register()"],
    exports: ["getWriterConnectionName", "getReaderConnectionName", "getWriterToken", "getReaderToken"],
  },
  {
    name: "TypeOrmDatabaseModule",
    category: "Database",
    kano: "Attractive",
    description: "TypeORM integration for PostgreSQL and MySQL with connection pooling",
    config: `database: {\n  type: 'postgres',\n  host: 'localhost',\n  port: 5432\n}`,
    methods: ["forFeature()", "register()"],
    exports: ["TypeOrmModule"],
  },
  {
    name: "DynamoDBModule",
    category: "Database",
    kano: "Attractive",
    description: "AWS DynamoDB integration with Dynamoose ODM",
    config: `database: {\n  type: 'dynamodb',\n  region: 'us-east-1'\n}`,
    methods: ["forFeature()", "register()"],
    exports: ["DynamooseModule"],
  },
  {
    name: "ElasticsearchModule",
    category: "Database",
    kano: "Attractive",
    description: "Elasticsearch integration for full-text search",
    config: `database: {\n  type: 'elasticsearch',\n  node: 'http://localhost:9200'\n}`,
    methods: ["register()"],
    exports: ["ElasticsearchService"],
  },
  {
    name: "CacheModule",
    category: "Cache",
    kano: "One-dimensional",
    description: "Multi-layer caching with Redis or Memcached backends",
    config: `cache: {\n  redis: { url: 'redis://localhost:6379' }\n}`,
    methods: ["register()", "forRoot()"],
    exports: ["CacheService", "CacheInterceptor"],
  },
  {
    name: "MemcachedModule",
    category: "Cache",
    kano: "Attractive",
    description: "Memcached caching backend with connection pooling",
    config: `cache: {\n  memcached: { servers: 'localhost:11211' }\n}`,
    methods: ["register()"],
    exports: ["MemcachedService"],
  },
  {
    name: "AuthModule",
    category: "Auth",
    kano: "Must-be",
    description: "JWT authentication with guard, strategy, and decorator setup",
    config: `auth: {\n  jwt: { secret: 'my-secret' }\n}`,
    methods: ["register()", "forRoot()"],
    exports: ["JwtAuthGuard", "JwtStrategy", "AuthService"],
  },
  {
    name: "RbacModule",
    category: "Auth",
    kano: "Attractive",
    description: "Role-based access control with decorators and guards",
    config: `auth: {\n  rbac: { roles: ['admin', 'user'] }\n}`,
    methods: ["register()"],
    exports: ["RolesGuard", "Roles"],
  },
  {
    name: "GrpcTransportModule",
    category: "Transport",
    kano: "One-dimensional",
    description: "gRPC transport layer with proto-loader integration",
    config: `transport: {\n  grpc: {\n    url: '0.0.0.0:5000',\n    package: 'myservice',\n    protoPath: 'proto/service.proto'\n  }\n}`,
    methods: ["register()", "createClient()"],
    exports: ["GrpcClientFactory"],
  },
  {
    name: "TcpTransportModule",
    category: "Transport",
    kano: "One-dimensional",
    description: "TCP transport for internal microservice communication",
    config: `transport: {\n  tcp: { host: '0.0.0.0', port: 4000 }\n}`,
    methods: ["register()"],
    exports: ["TcpClientProxy"],
  },
  {
    name: "NatsTransportModule",
    category: "Transport",
    kano: "Attractive",
    description: "NATS messaging transport for pub/sub patterns",
    config: `transport: {\n  nats: { url: 'nats://localhost:4222' }\n}`,
    methods: ["register()"],
    exports: ["NatsClientProxy"],
  },
  {
    name: "RabbitMQTransportModule",
    category: "Transport",
    kano: "Attractive",
    description: "RabbitMQ transport with queue management",
    config: `transport: {\n  rabbitmq: { url: 'amqp://localhost:5672' }\n}`,
    methods: ["register()"],
    exports: ["RabbitMQClientProxy"],
  },
  {
    name: "HealthModule",
    category: "Observability",
    kano: "Must-be",
    description: "Health check endpoints with Terminus integration",
    config: `health: { enabled: true }`,
    methods: ["register()"],
    exports: ["HealthController", "HealthIndicator"],
  },
  {
    name: "LoggerModule",
    category: "Observability",
    kano: "Must-be",
    description: "Structured logging with context and correlation IDs",
    config: `logger: {\n  level: 'info',\n  format: 'json'\n}`,
    methods: ["forRoot()"],
    exports: ["LoggerService"],
  },
  {
    name: "MetricsModule",
    category: "Observability",
    kano: "Attractive",
    description: "Prometheus metrics collection and /metrics endpoint",
    config: `metrics: { enabled: true, path: '/metrics' }`,
    methods: ["register()"],
    exports: ["MetricsService", "MetricsInterceptor"],
  },
  {
    name: "TracingModule",
    category: "Observability",
    kano: "Attractive",
    description: "Distributed tracing with OpenTelemetry",
    config: `tracing: {\n  serviceName: 'my-service',\n  exporter: 'jaeger'\n}`,
    methods: ["register()"],
    exports: ["TracingService", "TracingInterceptor"],
  },
  {
    name: "CircuitBreakerModule",
    category: "Resilience",
    kano: "Attractive",
    description: "Circuit breaker pattern for fault-tolerant service calls",
    config: `resilience: {\n  circuitBreaker: {\n    timeout: 3000,\n    errorThreshold: 50\n  }\n}`,
    methods: ["register()"],
    exports: ["CircuitBreakerService", "@CircuitBreaker()"],
  },
  {
    name: "RetryModule",
    category: "Resilience",
    kano: "One-dimensional",
    description: "Configurable retry with exponential backoff",
    config: `resilience: {\n  retry: { maxAttempts: 3, delay: 1000 }\n}`,
    methods: ["register()"],
    exports: ["RetryService", "@Retry()"],
  },
  {
    name: "RateLimiterModule",
    category: "Resilience",
    kano: "One-dimensional",
    description: "Request rate limiting per IP or user",
    config: `resilience: {\n  rateLimit: { windowMs: 60000, max: 100 }\n}`,
    methods: ["register()"],
    exports: ["RateLimiterGuard", "@RateLimit()"],
  },
  {
    name: "BullQueueModule",
    category: "Queue/Events",
    kano: "Attractive",
    description: "Bull queue integration for background job processing",
    config: `queue: {\n  redis: { url: 'redis://localhost:6379' }\n}`,
    methods: ["registerQueue()", "forRoot()"],
    exports: ["BullQueueService", "@Processor()"],
  },
  {
    name: "EventBusModule",
    category: "Queue/Events",
    kano: "One-dimensional",
    description: "In-process event bus for domain events",
    config: `events: { enabled: true }`,
    methods: ["register()"],
    exports: ["EventBusService", "@OnEvent()"],
  },
  {
    name: "CqrsModule",
    category: "Queue/Events",
    kano: "Attractive",
    description: "CQRS pattern with command and query buses",
    config: `cqrs: { enabled: true }`,
    methods: ["register()"],
    exports: ["CommandBus", "QueryBus", "EventBus"],
  },
  {
    name: "ConfigModule",
    category: "Core",
    kano: "Must-be",
    description: "Typed configuration with validation and .env support",
    config: `// Automatically loaded from createApp options`,
    methods: ["forRoot()", "forFeature()"],
    exports: ["ConfigService"],
  },
  {
    name: "ValidationModule",
    category: "Core",
    kano: "Must-be",
    description: "Request validation with class-validator pipes",
    config: `validation: {\n  whitelist: true,\n  forbidNonWhitelisted: true\n}`,
    methods: ["register()"],
    exports: ["ValidationPipe"],
  },
  {
    name: "SwaggerModule",
    category: "Core",
    kano: "One-dimensional",
    description: "Auto-generated OpenAPI documentation",
    config: `swagger: {\n  title: 'My API',\n  version: '1.0',\n  path: 'api'\n}`,
    methods: ["setup()"],
    exports: ["SwaggerDocument"],
  },
  {
    name: "TestingModule",
    category: "Testing",
    kano: "Must-be",
    description: "Testing utilities with module overrides and mocks",
    config: `// Used in test files with Test.createTestingModule()`,
    methods: ["createTestingModule()", "overrideProvider()"],
    exports: ["TestingModule", "MockFactory"],
  },
  {
    name: "E2ETestingModule",
    category: "Testing",
    kano: "One-dimensional",
    description: "End-to-end testing with supertest integration",
    config: `// Used in e2e test files`,
    methods: ["createE2EModule()"],
    exports: ["E2ETestHelper", "SupertestAgent"],
  },
  {
    name: "DockerModule",
    category: "DevOps",
    kano: "Must-be",
    description: "Docker and docker-compose generation for local development",
    config: `docker: {\n  enabled: true,\n  compose: true\n}`,
    methods: ["generate()"],
    exports: ["Dockerfile", "docker-compose.yml"],
  },
];

export const categories = [
  "Database",
  "Cache",
  "Auth",
  "Transport",
  "Observability",
  "Resilience",
  "Queue/Events",
  "Core",
  "Testing",
  "DevOps",
];

export const categoryColors: Record<string, string> = {
  Database: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  Cache: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  Auth: "bg-red-500/10 text-red-400 border-red-500/20",
  Transport: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  Observability: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  Resilience: "bg-orange-500/10 text-orange-400 border-orange-500/20",
  "Queue/Events": "bg-pink-500/10 text-pink-400 border-pink-500/20",
  Core: "bg-sky-500/10 text-sky-400 border-sky-500/20",
  Testing: "bg-teal-500/10 text-teal-400 border-teal-500/20",
  DevOps: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
};

export const kanoColors: Record<string, string> = {
  "Must-be": "bg-red-500/10 text-red-400",
  Attractive: "bg-green-500/10 text-green-400",
  "One-dimensional": "bg-yellow-500/10 text-yellow-400",
};
