import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ApiTestConfig, EndpointConfig, RecordedResponse } from '../types.js';
import { buildHeaders, buildUrl, ensureDir, getColors, pathSlug } from '../utils.js';

export interface LoadTestConfig {
  /** k6 stage definitions */
  stages?: { duration: string; target: number }[];
  /** p95 latency threshold in ms */
  p95Threshold?: number;
  /** max failure rate (0-1) */
  maxFailRate?: number;
  /** autocannon connections */
  connections?: number;
  /** autocannon duration in seconds */
  duration?: number;
}

const DEFAULT_STAGES = [
  { duration: '30s', target: 10 },
  { duration: '1m', target: 50 },
  { duration: '30s', target: 0 },
];

/**
 * Generate a k6 script for a single endpoint.
 */
function generateK6Script(
  endpoint: EndpointConfig,
  config: ApiTestConfig,
  loadConfig: LoadTestConfig,
): string {
  const url = buildUrl(config, endpoint);
  const headers = buildHeaders(config, endpoint);
  const stages = loadConfig.stages || DEFAULT_STAGES;
  const p95 = loadConfig.p95Threshold || 500;
  const failRate = loadConfig.maxFailRate || 0.05;

  const headersStr = JSON.stringify(headers, null, 4)
    .split('\n')
    .map((line, i) => (i === 0 ? line : '    ' + line))
    .join('\n');

  const stagesStr = stages
    .map(s => `    { duration: '${s.duration}', target: ${s.target} },`)
    .join('\n');

  let bodySection = '';
  if (endpoint.body && ['POST', 'PUT', 'PATCH'].includes(endpoint.method)) {
    const bodyStr = JSON.stringify(endpoint.body);
    bodySection = `, ${bodyStr}`;
  }

  const methodFn = endpoint.method === 'GET'
    ? `http.get('${url}', { headers })`
    : endpoint.method === 'DELETE'
      ? `http.del('${url}', null, { headers })`
      : `http.${endpoint.method.toLowerCase()}('${url}'${bodySection}, { headers })`;

  return `// Generated load test for ${endpoint.method} ${endpoint.path}
// Run: k6 run <this-file>
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
${stagesStr}
  ],
  thresholds: {
    http_req_duration: ['p(95)<${p95}'],
    http_req_failed: ['rate<${failRate}'],
  },
};

const headers = ${headersStr};

export default function () {
  const res = ${methodFn};
  check(res, {
    'status is 2xx': (r) => r.status >= 200 && r.status < 300,
    'response time < ${p95}ms': (r) => r.timings.duration < ${p95},
  });
  sleep(1);
}
`;
}

/**
 * Generate an autocannon config for a single endpoint.
 */
function generateAutocannonConfig(
  endpoint: EndpointConfig,
  config: ApiTestConfig,
  loadConfig: LoadTestConfig,
): object {
  const url = buildUrl(config, endpoint);
  const headers = buildHeaders(config, endpoint);

  const acConfig: Record<string, any> = {
    url,
    connections: loadConfig.connections || 10,
    duration: loadConfig.duration || 30,
    method: endpoint.method,
    headers,
  };

  if (endpoint.body && ['POST', 'PUT', 'PATCH'].includes(endpoint.method)) {
    acConfig.body = JSON.stringify(endpoint.body);
  }

  return acConfig;
}

/**
 * Generate load test scripts for all recorded endpoints.
 * Outputs k6 scripts and autocannon configs to `{outputDir}/load/`.
 */
export function generateLoadTests(
  recordings: RecordedResponse[],
  config: ApiTestConfig,
  loadConfig: LoadTestConfig = {},
): { files: string[]; dir: string } {
  const c = getColors();
  const outputDir = config.outputDir || './api-tests';
  const loadDir = join(outputDir, 'load');
  const files: string[] = [];

  console.log(c.bold('\nGenerating load test scripts...\n'));

  const autocannonConfigs: Record<string, object> = {};

  for (const recording of recordings) {
    if (recording.status === 0 || recording.status >= 500) continue;

    const slug = pathSlug(recording.endpoint);

    // k6 script
    const k6Script = generateK6Script(recording.endpoint, config, loadConfig);
    const k6Path = join(loadDir, 'k6', `${slug}.js`);
    ensureDir(k6Path);
    writeFileSync(k6Path, k6Script);
    files.push(k6Path);

    // autocannon config
    autocannonConfigs[slug] = generateAutocannonConfig(recording.endpoint, config, loadConfig);

    console.log(`  ${c.cyan(slug)} — k6 + autocannon`);
  }

  // Combined autocannon config
  const acPath = join(loadDir, 'autocannon', 'config.json');
  ensureDir(acPath);
  writeFileSync(acPath, JSON.stringify(autocannonConfigs, null, 2));
  files.push(acPath);

  // README
  const readmePath = join(loadDir, 'README.md');
  ensureDir(readmePath);
  writeFileSync(readmePath, `# Load Tests

Generated by @nestjs-boot/api-test.

## k6

Install: \`brew install k6\` or \`https://k6.io/docs/getting-started/installation/\`

Run a single test:
\`\`\`bash
k6 run load/k6/<endpoint>.js
\`\`\`

Run all:
\`\`\`bash
for f in load/k6/*.js; do k6 run "$f"; done
\`\`\`

## autocannon

Install: \`npm i -g autocannon\`

Run:
\`\`\`bash
autocannon -c 10 -d 30 <url>
\`\`\`

Or use the generated config:
\`\`\`bash
npx autocannon --config load/autocannon/config.json
\`\`\`
`);
  files.push(readmePath);

  console.log(`\n${c.green('✓')} Generated ${files.length} load test files in ${loadDir}\n`);

  return { files, dir: loadDir };
}
