/**
 * problem-details.ts — RFC 7807 / RFC 9457 Problem Details support.
 *
 * Optional format. Opt-in via BootOptions:
 * ```ts
 * BootModule.register({ response: { format: 'problem-details' } })
 * ```
 *
 * When enabled:
 * - HTTP responses use `Content-Type: application/problem+json`
 * - Envelope maps to `{ type, title, status, detail, instance, [extensions] }`
 *
 * When disabled (default): existing envelope format is unchanged.
 *
 * @see https://www.rfc-editor.org/rfc/rfc7807
 */

import { HttpException, HttpStatus } from '@nestjs/common';
import type { BootException } from './boot-exception';
import type { ErrorResponse } from './filters/all-exceptions.filter';

/** RFC 7807 Problem Details object. */
export interface ProblemDetails {
  /** URI reference identifying the problem type. */
  type: string;
  /** Short human-readable summary (should NOT change between occurrences). */
  title: string;
  /** HTTP status code. */
  status: number;
  /** Human-readable explanation specific to this occurrence. */
  detail?: string;
  /** URI reference for this specific occurrence (e.g. request path). */
  instance?: string;
  /** Extension fields — any additional context. */
  [key: string]: unknown;
}

/**
 * Base URI for problem type URIs generated by this library.
 * Override globally if you have a public docs site:
 *   ProblemDetailsFormatter.baseUri = 'https://docs.myapp.com/errors';
 */
export const DEFAULT_PROBLEM_BASE_URI = 'about:blank';

/**
 * Map HTTP status codes to RFC 7807 standard titles.
 */
const HTTP_STATUS_TITLES: Record<number, string> = {
  [HttpStatus.BAD_REQUEST]: 'Bad Request',
  [HttpStatus.UNAUTHORIZED]: 'Unauthorized',
  [HttpStatus.FORBIDDEN]: 'Forbidden',
  [HttpStatus.NOT_FOUND]: 'Not Found',
  [HttpStatus.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [HttpStatus.CONFLICT]: 'Conflict',
  [HttpStatus.GONE]: 'Gone',
  [HttpStatus.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [HttpStatus.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [HttpStatus.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [HttpStatus.NOT_IMPLEMENTED]: 'Not Implemented',
  [HttpStatus.BAD_GATEWAY]: 'Bad Gateway',
  [HttpStatus.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [HttpStatus.GATEWAY_TIMEOUT]: 'Gateway Timeout',
};

/**
 * Convert a BootException or HttpException to a Problem Details object.
 *
 * ```ts
 * const pd = toProblemDetails(exception, '/api/orders/123');
 * // {
 * //   type: 'about:blank',
 * //   title: 'Not Found',
 * //   status: 404,
 * //   detail: 'Order not found',
 * //   instance: '/api/orders/123',
 * //   code: 'ORDER_NOT_FOUND',
 * // }
 * ```
 */
export function toProblemDetails(
  error: BootException | HttpException | ErrorResponse,
  instance?: string,
  baseUri: string = DEFAULT_PROBLEM_BASE_URI,
): ProblemDetails {
  // Handle ErrorResponse (already-serialized envelope from filter)
  if (isErrorResponse(error)) {
    const title = HTTP_STATUS_TITLES[error.statusCode] ?? 'Error';
    const pd: ProblemDetails = {
      type: buildTypeUri(baseUri, error.code),
      title,
      status: error.statusCode,
      detail: error.message !== title ? error.message : undefined,
    };
    if (instance) pd.instance = instance;
    if (error.code) pd.code = error.code;
    if (error.details) pd.details = error.details;
    return pd;
  }

  // Handle HttpException / BootException
  const statusCode = error.getStatus();
  const title = HTTP_STATUS_TITLES[statusCode] ?? 'Error';
  const bootEx = error as unknown as BootException;
  const code: string | undefined = bootEx.code;
  const details: unknown[] | undefined = bootEx.details;

  const exResponse = error.getResponse();
  let detail: string | undefined;

  if (typeof exResponse === 'string') {
    detail = exResponse !== title ? exResponse : undefined;
  } else if (typeof exResponse === 'object' && exResponse !== null) {
    const resp = exResponse as Record<string, unknown>;
    const msg = typeof resp.message === 'string' ? resp.message : undefined;
    detail = msg && msg !== title ? msg : undefined;
  }

  const pd: ProblemDetails = {
    type: buildTypeUri(baseUri, code),
    title,
    status: statusCode,
  };
  if (detail) pd.detail = detail;
  if (instance) pd.instance = instance;
  if (code) pd.code = code;
  if (details && details.length > 0) pd.details = details;

  return pd;
}

/**
 * Check whether the response is already a serialized ErrorResponse
 * (i.e., came from the filter after the exception was caught).
 */
function isErrorResponse(obj: unknown): obj is ErrorResponse {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    typeof (obj as Record<string, unknown>).statusCode === 'number' &&
    typeof (obj as Record<string, unknown>).message === 'string' &&
    !((obj as unknown) instanceof HttpException)
  );
}

/**
 * Build a `type` URI for the Problem Details object.
 *
 * - If a stable error code is available, appends it as a fragment:
 *   `about:blank#AUTH_TOKEN_EXPIRED`
 * - Otherwise returns the base URI as-is (`about:blank`).
 *
 * If you host error documentation, set `baseUri` to your docs URL:
 *   `https://docs.myapp.com/errors#AUTH_TOKEN_EXPIRED`
 */
function buildTypeUri(baseUri: string, code?: string): string {
  if (!code) return baseUri;
  // Avoid double-fragment if baseUri already has one
  const separator = baseUri.includes('#') ? '/' : '#';
  return `${baseUri}${separator}${code}`;
}
